export const RESET = 'reset';

export const AUTH_USER = 'auth_user';
export const AUTH_ADMIN = 'auth_admin';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const RESET_ERROR = 'RESET_ERROR'

export const TRY_CONNECT = 'try_connect';

export const FETCH_PROFILE = 'fetch_profile';

export const CREATE_VOLUNTEER_CHANCE = 'CREATE_VOLUNTEER_CHANCE';
export const FETCH_ALL_VOLUNTEER_CHANCES = 'FETCH_ALL_VOLUNTEER_CHANCES';
export const FETCH_ONE_VOLUNTEER_CHANCE = 'FETCH_ONE_VOLUNTEER_CHANCE';
export const DELETE_ONE_VOLUNTEER_CHANCE = 'DELETE_ONE_VOLUNTEER_CHANCE';
export const DELETE_ONE_VOLUNTEER_GOBACK ='DELETE_ONE_VOLUNTEER_GOBACK';

export const CREATE_COURSE_CHANCE = 'CREATE_COURSE_CHANCE';
export const FETCH_ALL_COURSE_CHANCES = 'FETCH_ALL_COURSE_CHANCES';
export const FETCH_ONE_COURSE_CHANCE = 'FETCH_ONE_COURSE_CHANCE';
export const DELETE_ONE_COURSE_CHANCE = 'DELETE_ONE_COURSE_CHANCE';
export const DELETE_ONE_COURSE_GOBACK ='delete_one_course_goback';


export const CREATE_INTERNSHIP_CHANCE = 'CREATE_INTERNSHIP_CHANCE';
export const FETCH_ALL_INTERNSHIP_CHANCES = 'FETCH_ALL_INTERNSHIP_CHANCES';
export const FETCH_ONE_INTERNSHIP_CHANCE = 'FETCH_ONE_INTERNSHIP_CHANCE';
export const DELETE_ONE_INTERNSHIP_CHANCE = 'DELETE_ONE_INTERNSHIP_CHANCE';
export const DELETE_ONE_INTERNSHIP_GOBACK = 'DELETE_ONE_COURSE_GOBACK';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const EMAIL_SENT = 'EMAIL_SENT';
export const FAIL_TO_VERIFY_TOKEN = 'FAIL_TO_VERIFY_TOKEN';
export const SUCCESS_TO_VERIFY_TOKEN = 'SUCCESS_TO_VERIFY_TOKEN';
export const SUCCEED_TO_RESET_PASSWORD = 'SUCCEED_TO_RESET_PASSWORD';

export const SIGNUP_WITH_DATA = 'SIGNUP_WITH_DATA';

export const ASSIST_GET_COLLEGES = 'ASSIST_GET_COLLEGES';
export const ASSIST_GET_UNIVERSITIES = 'ASSIST_GET_UNIVERSITIES';
export const ASSIST_GET_MAJORS = 'ASSIST_GET_MAJORS';
export const ASSIST_RESET_MAJORS = 'ASSIST_RESET_MAJORS';
export const ASSIST_GET_AGREEMENT = 'ASSIST_GET_AGREEMENT';
export const ASSIST_RESET_AGREEMENT = 'ASSIST_RESET_AGREEMENT';

export const FETCH_ALL_APP = 'FETCH_ALL_APP';
export const CREATE_ONE_APP = 'CREATE_ONE_APP';
export const FETCH_ONE_APP = 'FETCH_ONE_APP';
export const UPDATE_ONE_APP = 'UPDATE_ONE_APP';
export const FETCH_ALL_APP_OF_ONE = 'FETCH_ALL_APP_OF_ONE';
export const RESET_APP = 'RESET_APP';
export const FAIL_APP_ACTION = 'FAIL_APP_ACTION';